# Generated by Django 3.0.3 on 2020-02-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0002_auto_20200223_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socks',
            new_name='Sock',
        ),
    ]
