# Generated by Django 3.0.3 on 2020-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0003_auto_20200223_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sock',
            name='isHot',
            field=models.BooleanField(default=False),
        ),
    ]
