# Generated by Django 3.0.3 on 2020-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0004_sock_ishot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sock',
            name='price',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
